name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch: # allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install -g eas-cli
          npm install

      - name: Log in to Expo
        run: eas login --token ${{ secrets.EAS_TOKEN }}

      - name: Build APK
        run: eas build --platform android --profile production --non-interactive

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: |
            ./android/app/build/outputs/**/*.apk
